name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted # Change this if you're using a self-hosted runner

    strategy:
      matrix:
        node-version: [22.x] # Include versions relevant to your project

    steps:
    # Step 1: Checkout code
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Run the app
    - name: Start the Application
      run: npm start
